### ISSUE TITLE
How to import the library in Eclipse? Is it Possible???

### ISSUE THREAD

**Issue by Abhinab01** [frakbot/CreditsRoll#1]
Hello Frakbot, this library seems very interesting and I looking forward to use it in my Project,
But the problem is that Im still using Eclipse for my current project and I don't know how to import your Library in Eclipse.

Any kind of help is highly appreciated. :)

Thank You.

**Comment by rock3r** [comment]
Using Eclipse is **officially _not_ supported**.

I am sorry but I don't use Eclipse and can't/won't do any effort to support ADT and other legacy systems. The library is using Gradle and works in IntelliJ/Android Studio, which is the official Android IDE. You might be able somehow to make things work in Eclipse by copy/pasting manually the code or some other black magic, but besides that, I don't know.

**Comment by Abhinab01** [comment]
It's Fine, I try to figure out something else... Anyways thanks a lot.... :)
