### ISSUE TITLE
not support the theme Theme.AppCompat.Light.NoActionBar

### ISSUE THREAD

**Issue by caixuejian** [frakbot/CreditsRoll#2]
I want you to help me solve the problem.  thanks!

**Comment by rock3r** [comment]
I am afraid this issue doesn't make sense as this is a view and it doesn't influence themes in any way.

Fix your app's code/theme and whatever unrelated issue you think you're having with this library will disappear.

If you _do_ find a bug in this library please spend the time coming up with a proper bug report and a PR to address said issue, and I will be happy to merge it.
